# This rule is not used by the project kube-drift itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over drift.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-drift
    app.kubernetes.io/managed-by: kustomize
  name: driftpolicy-admin-role
rules:
- apiGroups:
  - drift.my.domain
  resources:
  - driftpolicies
  verbs:
  - '*'
- apiGroups:
  - drift.my.domain
  resources:
  - driftpolicies/status
  verbs:
  - get
