apiVersion: drift.my.domain/v1alpha1
kind: DriftPolicy
metadata:
  labels:
    app.kubernetes.io/name: kube-drift
    app.kubernetes.io/managed-by: kustomize
  name: driftpolicy-imad
spec:
  targetRef:
    kind: Deployment
    name: nginx
    namespace: default
  syncSource:
    repoUrl: https://github.com/imad-elbouhati/kube-drift
    path: /root/path/nginx.yaml
    revision: e3f5fe3
